-- CASDA-3835 need to store all timestamp columns as TIMESTAMP WITH TIME ZONE data type.

ALTER TABLE casda.cached_file ALTER COLUMN unlock SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.cached_file ALTER COLUMN last_modified SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE casda.catalogue ALTER COLUMN last_modified SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.catalogue ALTER COLUMN time_obs SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.catalogue ALTER COLUMN deposit_state_changed SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE casda.continuum_component ALTER COLUMN last_modified SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE casda.data_access_job ALTER COLUMN created_timestamp SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.data_access_job ALTER COLUMN available_timestamp SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.data_access_job ALTER COLUMN expired_timestamp SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.data_access_job ALTER COLUMN last_modified SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE casda.data_access_job_image_cube ALTER COLUMN last_modified SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE casda.image_cube ALTER COLUMN last_modified SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.image_cube ALTER COLUMN deposit_state_changed SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE casda.measurement_set ALTER COLUMN last_modified SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.measurement_set ALTER COLUMN deposit_state_changed SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE casda.observation ALTER COLUMN obs_start SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.observation ALTER COLUMN obs_end SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.observation ALTER COLUMN last_modified SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.observation ALTER COLUMN released_date SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.observation ALTER COLUMN deposit_started SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.observation ALTER COLUMN deposit_state_changed SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.observation ALTER COLUMN metadata_file_deposit_state_changed SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE casda.observation_project ALTER COLUMN last_modified SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE casda.project ALTER COLUMN last_modified SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE casda.validation_file ALTER COLUMN last_modified SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE casda.validation_file ALTER COLUMN deposit_state_changed SET DATA TYPE TIMESTAMP WITH TIME ZONE;