-- Table creation script for sl absorption
-- Generated by CASDA Data Deposit on 2015-04-07

CREATE table casda.spectral_line_absorption (
 id BIGSERIAL PRIMARY KEY,
 catalogue_id  BIGINT references casda.catalogue(id),
 sbid    INTEGER references casda.observation(sbid),
 project_id    BIGINT references casda.project(id),
 image_id VARCHAR(50),
 date_time_ut VARCHAR(50),
 cont_component_id VARCHAR(22),
 cont_flux REAL,
 object_id VARCHAR(24),
 object_name VARCHAR(15),
 ra_hms_cont VARCHAR(12),
 dec_dms_cont VARCHAR(13),
 ra_deg_cont double precision,
 dec_deg_cont double precision,
 ra_deg_cont_err REAL,
 dec_deg_cont_err REAL,
 freq_uw REAL,
 freq_uw_err REAL,
 freq_w REAL,
 freq_w_err REAL,
 z_hi_uw REAL,
 z_hi_uw_err REAL,
 z_hi_w REAL,
 z_hi_w_err REAL,
 z_hi_peak REAL,
 z_hi_peak_err REAL,
 w50 REAL,
 w50_err REAL,
 w20 REAL,
 w20_err REAL,
 rms_imagecube REAL,
 opt_depth_peak REAL,
 opt_depth_peak_err REAL,
 opt_depth_int REAL,
 opt_depth_int_err REAL,
 flag_s1 smallint,
 flag_s2 smallint,
 flag_s3 smallint,
 quality_level character varying(15) DEFAULT 'NOT_VALIDATED'::character varying,
 released_date timestamp with time zone,
 last_modified    TIMESTAMP DEFAULT now()
);

CREATE INDEX ON casda.spectral_line_absorption(id);
CREATE INDEX ON casda.spectral_line_absorption(catalogue_id); 
CREATE INDEX ON casda.spectral_line_absorption(sbid); 
CREATE INDEX ON casda.spectral_line_absorption(project_id); 
CREATE INDEX ON casda.spectral_line_absorption(object_id); 
CREATE INDEX ON casda.spectral_line_absorption(object_name); 
CREATE INDEX ON casda.spectral_line_absorption(ra_hms_cont); 
CREATE INDEX ON casda.spectral_line_absorption(dec_dms_cont); 
CREATE INDEX ON casda.spectral_line_absorption(ra_deg_cont); 
CREATE INDEX ON casda.spectral_line_absorption(dec_deg_cont);
CREATE INDEX ON casda.spectral_line_absorption(freq_uw);
CREATE INDEX ON casda.spectral_line_absorption(freq_w);
CREATE INDEX ON casda.spectral_line_absorption(z_hi_uw);
CREATE INDEX ON casda.spectral_line_absorption(z_hi_w);
CREATE INDEX ON casda.spectral_line_absorption(z_hi_peak);
CREATE INDEX ON casda.spectral_line_absorption(rms_imagecube);
CREATE INDEX ON casda.spectral_line_absorption(opt_depth_peak);
CREATE INDEX ON casda.spectral_line_absorption(opt_depth_int);
CREATE INDEX ON casda.spectral_line_absorption(flag_s1);
CREATE INDEX ON casda.spectral_line_absorption(flag_s2);
CREATE INDEX ON casda.spectral_line_absorption(flag_s3);


COMMENT ON TABLE casda.spectral_line_absorption is 'Describes each spectral line absorption to be archived ';
COMMENT ON COLUMN casda.spectral_line_absorption.id  is 'The primary key';
COMMENT ON COLUMN casda.spectral_line_absorption.catalogue_id is 'The foreign key into the Catalogue table';
COMMENT ON COLUMN casda.spectral_line_absorption.sbid is 'The foreign key into the Observation table (using the sbid column)';
COMMENT ON COLUMN casda.spectral_line_absorption.project_id is 'The foreign key into the Project table';
COMMENT ON COLUMN casda.spectral_line_absorption.image_id is 'identifies the image that the detection came from.';
COMMENT ON COLUMN casda.spectral_line_absorption.date_time_ut is 'UTC of the observation';
COMMENT ON COLUMN casda.spectral_line_absorption.cont_component_id is 'Component identifier for the background continuum source ';
COMMENT ON COLUMN casda.spectral_line_absorption.cont_flux is 'Nominal continuum flux, taken from continuum cube';
COMMENT ON COLUMN casda.spectral_line_absorption.object_id is 'Ident for objects';
COMMENT ON COLUMN casda.spectral_line_absorption.object_name is 'Object name';
COMMENT ON COLUMN casda.spectral_line_absorption.ra_hms_cont is 'J2000 Right Ascension in hours, mins, secs (hh:mm:ss.SSS) format';
COMMENT ON COLUMN casda.spectral_line_absorption.dec_dms_cont is 'J2000 Declination in degrees, arcmin, arcsec (dd:mm:ss.SSS) format';
COMMENT ON COLUMN casda.spectral_line_absorption.ra_deg_cont is 'J2000 Right Ascension in decimal degrees';
COMMENT ON COLUMN casda.spectral_line_absorption.dec_deg_cont is 'J2000 Declination in decimal degrees';
COMMENT ON COLUMN casda.spectral_line_absorption.ra_deg_cont_err is 'Error in RA';
COMMENT ON COLUMN casda.spectral_line_absorption.dec_deg_cont_err is 'Error in Declination';
COMMENT ON COLUMN casda.spectral_line_absorption.freq_uw is 'Unweighted mean frequency from all channels, in the Barycentric reference system';
COMMENT ON COLUMN casda.spectral_line_absorption.freq_uw_err is 'Error in freq_uw';
COMMENT ON COLUMN casda.spectral_line_absorption.freq_w is 'Weighted mean frequency from all channels, where the weight is the optical depth, in the Barycentric reference system';
COMMENT ON COLUMN casda.spectral_line_absorption.freq_w_err is 'Error in freq_uw';
COMMENT ON COLUMN casda.spectral_line_absorption.z_hi_uw is 'Redshift of the object derived from freq_uw, assuming HI 21cm, with solar barycentric reference system ';
COMMENT ON COLUMN casda.spectral_line_absorption.z_hi_uw_err is 'Error is z_hi_uw';
COMMENT ON COLUMN casda.spectral_line_absorption.z_hi_w is 'Redshift of the object derived from freq_w, assuming HI 21cm, with  solar barycentric reference system ';
COMMENT ON COLUMN casda.spectral_line_absorption.z_hi_w_err is 'Error in z_hi_w';
COMMENT ON COLUMN casda.spectral_line_absorption.z_hi_peak is 'Redshift from the location of peak optical depth, assuming HI 21cm, with solar barycentric reference system ';
COMMENT ON COLUMN casda.spectral_line_absorption.z_hi_peak_err is 'Error in z_hi_peak';
COMMENT ON COLUMN casda.spectral_line_absorption.w50 is 'Frequency width corresponding to 50% of the peak optical depth';
COMMENT ON COLUMN casda.spectral_line_absorption.w50_err is 'Error in w_50';
COMMENT ON COLUMN casda.spectral_line_absorption.w20 is 'Frequency width corresponding to 20% of the peak optical depth';
COMMENT ON COLUMN casda.spectral_line_absorption.w20_err is 'Error in w20';
COMMENT ON COLUMN casda.spectral_line_absorption.rms_imagecube is 'Estimate of the rms noise level in the data cube around this object';
COMMENT ON COLUMN casda.spectral_line_absorption.opt_depth_peak is 'Peak optical depth, for an assumed covering factor of one';
COMMENT ON COLUMN casda.spectral_line_absorption.opt_depth_peak_err is 'Error in peak optical depth';
COMMENT ON COLUMN casda.spectral_line_absorption.opt_depth_int is 'Integrated optical depth, for an assumed covering factor of one';
COMMENT ON COLUMN casda.spectral_line_absorption.opt_depth_int_err is 'Error in opt_depth_int';
COMMENT ON COLUMN casda.spectral_line_absorption.flag_s1 is 'Placeholder field for spectral line absorption flag (1)';
COMMENT ON COLUMN casda.spectral_line_absorption.flag_s2 is 'Placeholder field for spectral line absorption flag (2)';
COMMENT ON COLUMN casda.spectral_line_absorption.flag_s3 is 'Placeholder field for spectral line absorption flag (3)';
COMMENT ON COLUMN casda.spectral_line_absorption.quality_level is 'Indicator of quality level, updated by validators';
COMMENT ON COLUMN casda.spectral_line_absorption.released_date is 'The date that the spectral line absorption data product was released';
COMMENT ON COLUMN casda.spectral_line_absorption.last_modified is 'When the row was last modified (usually via an insert)';

INSERT INTO casda.tables (schema_name, table_name, table_type, db_schema_name, db_table_name, description, scs_enabled )
VALUES ('casda', 'casda.spectral_line_absorption', 'table', 'casda', 'spectral_line_absorption', '', true);

INSERT INTO casda.columns (column_order, column_name, table_name, datatype, size, principal, indexed, std, description, ucd, unit, scs_verbosity )
VALUES 
(1, 'id', 'casda.spectral_line_absorption', 'BIGINT', 19, 1, 1, 1, 'Primary key', 'meta.record', null, 1),
(2, 'catalogue_id', 'casda.spectral_line_absorption', 'BIGINT', 19, 1, 1, 1, 'Catalogue identifier', null, null, 3),
(3, 'sbid', 'casda.spectral_line_absorption', 'BIGINT', 15, 1, 1, 1, 'Scheduling Block identifier', null, null, 3),
(4, 'project_id', 'casda.spectral_line_absorption', 'BIGINT', 19, 1, 1, 1, 'Project identifier', null, null, 3),
(5, 'image_id', 'casda.spectral_line_absorption', 'VARCHAR', 50, 0, 0, 1, 'identifies the image that the detection came from', 'meta.id', '--', 3),
(6, 'date_time_ut', 'casda.spectral_line_absorption', 'VARCHAR', 50, 0, 0, 1, 'UTC of the observation', 'time.start', '--', 3),
(7, 'cont_component_id', 'casda.spectral_line_absorption', 'VARCHAR', 22, 0, 0, 1, 'Component identifier for the background continuum source', 'meta.id.parent', '--', 3),
(8, 'cont_flux', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Nominal continuum flux, taken from continuum cube', 'phot.flux.density;em.radio;spect.continuum', 'mJy', 3),
(9, 'object_id', 'casda.spectral_line_absorption', 'VARCHAR', 24, 0, 0, 1, 'Ident for objects', 'meta.id;meta.main', '--', 3),
(10, 'object_name', 'casda.spectral_line_absorption', 'VARCHAR', 15, 0, 0, 1, 'Object name', 'meta.id', null, 3),
(11, 'ra_hms_cont', 'casda.spectral_line_absorption', 'VARCHAR', 12, 0, 0, 1, 'J2000 Right Ascension in hours, mins, secs (hh:mm:ss.SSS) format', 'pos.eq.ra', null, 3),
(12, 'dec_dms_cont', 'casda.spectral_line_absorption', 'VARCHAR', 13, 0, 0, 1, 'J2000 Declination in degrees, arcmin, arcsec (dd:mm:ss.SSS) format', 'pos.eq.dec', null, 3),
(13, 'ra_deg_cont', 'casda.spectral_line_absorption', 'DOUBLE', 10, 1, 1, 1, 'J2000 Right Ascension in decimal degrees', 'pos.eq.ra;meta.main', 'deg', 1),
(14, 'dec_deg_cont', 'casda.spectral_line_absorption', 'DOUBLE', 10, 1, 1, 1, 'J2000 Declination in decimal degrees', 'pos.eq.dec;meta.main', 'deg', 1),
(15, 'ra_deg_cont_err', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Error in RA', 'stat.error;pos.eq.ra', 'arcsec', 3),
(16, 'dec_deg_cont_err', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Error in Declination', 'stat.error;pos.eq.dec', 'arcsec', 3),
(17, 'freq_uw', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Unweighted mean frequency from all channels, in the Barycentric reference system', 'em.freq;meta.main', 'MHz', 3),
(18, 'freq_uw_err', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Error in freq_uw', 'stat.error;em.freq;meta.main', 'MHz', 3),
(19, 'freq_w', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Weighted mean frequency from all channels, where the weight is the optical depth, in the Barycentric reference system', 'em.freq', 'MHz', 3),
(20, 'freq_w_err', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Error in freq_uw', 'stat.error;em.freq', 'MHz', 3),
(21, 'z_hi_uw', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Redshift of the object derived from freq_uw, assuming HI 21cm, with solar barycentric reference system', 'src.redshift;em.line.HI;meta.main', null, 3),
(22, 'z_hi_uw_err', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Error is z_hi_uw', 'stat.error;src.redshift;em.line.HI;meta.main', null, 3),
(23, 'z_hi_w', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Redshift of the object derived from freq_w, assuming HI 21cm, with  solar barycentric reference system', 'src.redshift;em.line.HI', null, 3),
(24, 'z_hi_w_err', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Error in z_hi_w', 'stat.error;src.redshift;em.line.HI', null, 3),
(25, 'z_hi_peak', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Redshift from the location of peak optical depth, assuming HI 21cm, with solar barycentric reference system', 'src.redshift;em.line.HI;phys.absorption.opticalDepth;stat.max', null, 3),
(26, 'z_hi_peak_err', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Error in z_hi_peak', 'stat.error;src.redshift;em.line.HI;phys.absorption.opticalDepth;stat.max', null, 3),
(27, 'w50', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Frequency width corresponding to 50% of the peak optical depth', 'phys.absorption;spect.line.width;em.freq', 'kHz', 3),
(28, 'w50_err', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Error in w_50', 'stat.error;phys.absorption;spect.line.width;em.freq', 'kHz', 3),
(29, 'w20', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Frequency width corresponding to 20% of the peak optical depth', 'phys.absorption;askap:spect.line.width20;em.freq', 'kHz', 3),
(30, 'w20_err', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Error in w20', 'stat.error;phys.absorption;askap:spect.line.width20;em.freq', 'kHz', 3),
(31, 'rms_imagecube', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Estimate of the rms noise level in the data cube around this object', 'stat.stdev;phot.flux.density', 'mJy/beam', 3),
(32, 'opt_depth_peak', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Peak optical depth, for an assumed covering factor of one', 'phys.absorption.opticalDepth;stat.max', null, 3),
(33, 'opt_depth_peak_err', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Error in peak optical depth', 'stat.error;phys.absorption.opticalDepth;stat.max', null, 3),
(34, 'opt_depth_int', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Integrated optical depth, for an assumed covering factor of one', 'phys.absorption.opticalDepth;askap:arith.integrated', null, 3),
(35, 'opt_depth_int_err', 'casda.spectral_line_absorption', 'REAL', 10, 0, 0, 1, 'Error in opt_depth_int', 'stat.error;phys.absorption.opticalDepth;askap:arith.integrated', 'km/s', 3),
(36, 'flag_s1', 'casda.spectral_line_absorption', 'INTEGER', 15, 0, 0, 1, 'Placeholder field for spectral line absorption flag (1)', 'meta.code', null, 3),
(37, 'flag_s2', 'casda.spectral_line_absorption', 'INTEGER', 15, 0, 0, 1, 'Placeholder field for spectral line absorption flag (2)', 'meta.code', null, 3),
(38, 'flag_s3', 'casda.spectral_line_absorption', 'INTEGER', 15, 0, 0, 1, 'Placeholder field for spectral line absorption flag (3)', 'meta.code', null, 3),
(37, 'quality_level', 'casda.spectral_line_absorption', 'INTEGER', 1000, 1, 0, 1, 'Indicator of quality level', 'meta.note', null, 3),
(37, 'released_date', 'casda.spectral_line_absorption', 'TIMESTAMP', 24, 1, 0, 1, 'Date the catalogue was released', '', null, 3)
;

INSERT INTO casda.keys (key_id, from_table, target_table, description )
VALUES ((SELECT count(*) + 1 from casda.keys), 'casda.spectral_line_absorption', 'casda.catalogue', 'Foreign key from spectral_line_absorption to catalogue table');

INSERT INTO casda.key_columns (id, key_id, from_column, target_column, from_table, target_table )
VALUES ((SELECT count(*) + 1 from casda.key_columns), (SELECT key_id FROM casda.keys where from_table = 'casda.spectral_line_absorption' and target_table = 'casda.catalogue'), 'catalogue_id', 'id', 'casda.spectral_line_absorption', 'casda.catalogue');